### ISSUE TITLE
Documentation recommendation: MGM hostname

### ISSUE THREAD

**Issue by alyhasansakr** [InterDigitalInc/AdvantEDGE#11]
At "[AdvantEDGE/wiki/state-transfer](https://github.com/InterDigitalInc/AdvantEDGE/wiki/state-transfer)" the hostname of the MGM and the base path are not mentioned in the page, you can get them from the code but it would be a lot easier if they were explicitly mentioned in this page.

**Comment by dilallkx** [comment]
Added **MG Manager URIs** section in wiki page with this information.
