### ISSUE TITLE
Location Service basepath does not match the API

### ISSUE THREAD

**Issue by roymx** [InterDigitalInc/AdvantEDGE#14]
**Describe the bug**
Basepath in the API is "exampleAPI" and basepath in the code is "etsi-013"

**To Reproduce**
This command does not work
curl -X GET http://127.0.0.1:30007/exampleAPI/location/v1/zones

**Expected behavior**
- API file matches the generated code.
- API file uses the "etsi-013" basepath

**AdvantEDGE versions**
V1.1.0

**AdvantEDGE node:**
Information on the node where AdvantEDGE is running
 - OS: Ubuntu
 - Node IP address: 10.3.16.75
 - Version 16.04LTS

**Additional context**
meepctl version all
Using repo config file: /home/englab/AdvantEDGE/.meepctl-repocfg.yaml
Using meepctl config file: /home/englab/.meepctl.yaml
{
  "name": "meepctl",
  "version": "1.1.0"
}
{
  "name": ".meepctl-repocfg.yaml",
  "version": "1.1.0"
}
{
  "name": "helm client",
  "version": "v2.9.1",
  "id": "20adb27c7c5868466912eebdf6664e7390ebe710"
}
{
  "name": "helm server",
  "version": "v2.9.1",
  "id": "20adb27c7c5868466912eebdf6664e7390ebe710"
}
{
  "name": "docker client",
  "version": "18.09.7",
  "id": "2d0083d"
}
{
  "name": "docker server",
  "version": "18.09.7",
  "id": "2d0083d"
}
{
  "name": "k8s client",
  "version": "v1.14.1",
  "id": "b7394102d6ef778017f2ca4046abbaa23b88c290"
}
{
  "name": "k8s server",
  "version": "v1.14.1",
  "id": "b7394102d6ef778017f2ca4046abbaa23b88c290"
}
{
  "name": "weave",
  "version": "weaveworks/weave-kube:2.5.1",
  "id": "103e37b504631f7c762ef6baa79b3e7d2d2cf718accbf659e7cae933b6ca937c"
}
{
  "name": "couchdb",
  "version": "couchdb:2.1.1",
  "id": "c467d1c2a172bf0c8172b2e1c760686d0c7656d786e6874a9de12f2d0a3a38e7"
}
{
  "name": "elasticsearch-curator",
  "version": "quay.io/pires/docker-elasticsearch-curator:5.5.4",
  "id": "6474a59ae7fc836af6c48dd045d8bb0c310a663f68a0f225a1a5186ed1707ce8"
}
{
  "name": "elasticsearch",
  "version": "docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.3",
  "id": "e3b2f1a2da191cf8e3e43d2a871bfa40ffc965202d84760a7c8b3762a71e5e43"
}
{
  "name": "filebeat",
  "version": "docker.elastic.co/beats/filebeat:6.4.1",
  "id": "886ebbfa1bcefcc3e3821c41c62353e98f85a0a88a1d17d9a2978c0b4678ff2a"
}
{
  "name": "kibana",
  "version": "docker.elastic.co/kibana/kibana-oss:6.4.3",
  "id": "29689ebc49ab5cee62c62fc2f34b3d1da6563c2781bcfd1214527b5d3f411a08"
}
{
  "name": "kube-state-metrics",
  "version": "quay.io/coreos/kube-state-metrics:v1.4.0",
  "id": "6685342bbd645754b1aabdd9b663691109ec680645af261288289e62571ac201"
}
{
  "name": "meep-ctrl-engine",
  "version": "meep-docker-registry:30001/meep-ctrl-engine:latest",
  "id": "ccc3682ef52cecd0b9304dc25cf705d846cc4f8de489901ce98519be80ba9f5e",
  "build": "6d5f5070072bd78db4ab18de2ccd56d6dd5ef48f7b7b9577c163a6fd90be4119"
}
{
  "name": "meep-webhook",
  "version": "meep-docker-registry:30001/meep-webhook:latest",
  "id": "5b9fd3b086dce6a887d5401576b295c397691e61d0165ff6dc173248d951cc07",
  "build": "d8b283dd0eca3146d3b597384a364ba4a20c0d1fdc0864ac58d43fa48f9caa10"
}
{
  "name": "meep-mg-manager",
  "version": "meep-docker-registry:30001/meep-mg-manager:latest",
  "id": "77f051261f8b77520ba6339a733e635498284ea099b5e183a8f4951dcf591cd1",
  "build": "4c8383d0b881156410e293e779a63f2bd7d7036556132ebd8fc955fd762f7e8b"
}
{
  "name": "meep-mon-engine",
  "version": "meep-docker-registry:30001/meep-mon-engine:latest",
  "id": "1b5a5b86b7770e9a5a5444708bb26349fa7c878e2eed97801dd616be720221eb",
  "build": "e12a2dbde8ee349a0443ad0d66bcac67e62b43d6b3fd761b10352686ee14f96b"
}
{
  "name": "meep-redis",
  "version": "redislabs/rejson:latest",
  "id": "e855184c1255d160959d602b318a2ef39ffdfef7baa92c88897857ba09245d51"
}
{
  "name": "meep-tc-engine",
  "version": "meep-docker-registry:30001/meep-tc-engine:latest",
  "id": "8f8eebb288186726095d1710cf50a961f23ff8735f18027d0a4235728a3220ba",
  "build": "6dc5be761074ae9f08ab0cb3362837c91c7fff0e49fc9182d894ff63533740bc"
}
{
  "name": "metricbeat",
  "version": "docker.elastic.co/beats/metricbeat:6.4.3",
  "id": "91902ed10ab59a66fae475c9faf73cf22d108ce8182fa20d702a4fa6cd75280d"
}

**Comment by pastorsx** [comment]
All references to the URLs in the APIs where "exampleAPI" appeared were all changed to be "etsi-013". This better reflects the code expectations.

This was merged and is included in the release AdvantEDGE 1.2.0
