### ISSUE TITLE
Abnormally Long Pod Deployment Time in 1.6

### ISSUE THREAD

**Issue by juan-castrillon** [InterDigitalInc/AdvantEDGE#246]
**Describe the bug**
Any operation that includes pod deployments takes a long amount of time. For example, in my case this operations take 15 minutes  (almost exactly) each:
- Deploying Advantedge core
- Creating a new sandbox
- Deploying an scenario into the sandbox (Deploy the applications) : The delayed behavior here seems randomly occasional (Same scenario, same sandbox, some times will deploy quickly, some will take 15 minutes. Just for making this issue, the first 3 times was quick deployment and the 4th was 15 minute wait, no changes in the scenario)

Pods are stuck in an `Init` state for this time. This behavior is also reported by a fellow colleague working on a different virtual machine

**To Reproduce**
1. Deploy AdvantEDGE core
2. Run `kubectl get pods --all-namespaces | grep meep` to verify  that only after 15 minutes, pods are in `Running` state
3. Create a new sandbox
4. Run `kubectl get pods --all-namespaces` to verify that only after 15 minutes, sandbox pods are in `Running` state
5. Deploy a simple scenario with one client application (Running on a UE) and one edge aplication.
6. Run `kubectl get pods --all-namespaces` to verify only after 15 minutes, application pods are in `Running` state

**Expected behavior**
Waiting time, specially for deploying an scenario should not be this long every time. 

**Screenshots**
![image](https://user-images.githubusercontent.com/64461123/117542587-83fd0400-b019-11eb-8161-5baafff4d559.png)
![image](https://user-images.githubusercontent.com/64461123/117542705-f837a780-b019-11eb-84ad-79a1b163a552.png)
![image](https://user-images.githubusercontent.com/64461123/117543131-ca536280-b01b-11eb-97cf-b7628d605b25.png)
![image](https://user-images.githubusercontent.com/64461123/117543305-857bfb80-b01c-11eb-9419-72c932ef0a38.png)
![image](https://user-images.githubusercontent.com/64461123/117544405-93804b00-b021-11eb-8e19-f579e4e626d9.png)
![image](https://user-images.githubusercontent.com/64461123/117544520-31741580-b022-11eb-8a81-187359eee1cb.png)

**Scenario**
Behavior was observed with different scenarios but I can provide the YAML file of the scenario used for this screenshots

**AdvantEDGE versions**
```
{
  "name": "meepctl",
  "version": "1.6.0"
}
{
  "name": ".meepctl-repocfg.yaml",
  "version": "1.6.0"
}
{
  "name": "meep-cert-manager",
  "version": "NA"
}
{
  "name": "couchdb",
  "version": "couchdb:2.1.1",
  "id": "c467d1c2a172bf0c8172b2e1c760686d0c7656d786e6874a9de12f2d0a3a38e7"
}
{
  "name": "docker-registry",
  "version": "registry:2.7.1",
  "id": "5bb9b919833aa955dfe1d1121cc038330b025ec6506ce47066c9192927e3dc3d"
}
{
  "name": "grafana",
  "version": "grafana/grafana:6.5.2",
  "id": "33d78da1e5f3f74833de2ba9303ddcf995da551850cf431696efd271e7928f9e"
}
{
  "name": "meep-influxdb",
  "version": "influxdb:1.7.6-alpine",
  "id": "4ba363315807fc6e35e98bc9d4760f417a681e4d3a547a0b24b135c56af96376"
}
{
  "name": "nginx-ingress-controller",
  "version": "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0",
  "id": "b312c91d0de688a21075078982b5e3a48b13b46eda4df743317d3059fc3ca0d9"
}
{
  "name": "kube-state-metrics",
  "version": "quay.io/coreos/kube-state-metrics:v1.4.0",
  "id": "6685342bbd645754b1aabdd9b663691109ec680645af261288289e62571ac201"
}
{
  "name": "meep-open-map-tiles",
  "version": "NA"
}
{
  "name": "meep-postgis",
  "version": "postgis/postgis:12-3.0",
  "id": "71acda16357f2973034483a4a8363cc9499061120b592bcc3b7f2fbed82da621"
}
{
  "name": "meep-redis",
  "version": "redislabs/rejson:1.0.4",
  "id": "08f1d67dacae984c17aa9869b05415abd453cdd642623718301267455d3e2696"
}
{
  "name": "helm",
  "version": "v3.3.4",
  "id": "a61ce5633af99708171414353ed49547cf05013d"
}
{
  "name": "docker client",
  "version": "19.03.14",
  "id": "5eb3275d40"
}
{
  "name": "docker server",
  "version": "19.03.14",
  "id": "5eb3275d40"
}
{
  "name": "k8s client",
  "version": "v1.19.1",
  "id": "206bcadf021e76c27513500ca24182692aabd17e"
}
{
  "name": "k8s server",
  "version": "v1.19.9",
  "id": "9dd794e454ac32d97cde41ae10be801ae98f75df"
}
{
  "name": "weave",
  "version": "weaveworks/weave-kube:2.8.1",
  "id": "d797338e7beb17222e10757b71400d8471bdbd9be13b5da38ce2ebf597fb4e63"
}
{
  "name": "meep-ingress-certs",
  "version": "NA"
}
{
  "name": "meep-mon-engine",
  "version": "meep-docker-registry:30001/meep-mon-engine:latest",
  "id": "595f67feecca5d1dd0e17dbf2f04a4a3c62068ffaf1e2ac2df72f55d5e323328",
  "build": "3ef4b4c2be74ff0d2c31468d764f9761ff6e7265b278ffb0ca511f9bd2cc2981"
}
{
  "name": "meep-platform-ctrl",
  "version": "meep-docker-registry:30001/meep-platform-ctrl:latest",
  "id": "380a13176c3434ab1db4928b3a220e94bb76f23edbfe195e40a7c265c223ac15",
  "build": "932abe8f68a0021ed35b18d936d2c6399f3a51012ddff87a7560f17fcbd798dd"
}
{
  "name": "meep-virt-engine",
  "version": "meep-docker-registry:30001/meep-virt-engine:latest",
  "id": "f70dea83788e8523534a480c76065e9bf47b4ace620521081e584eb114d2be8c",
  "build": "9ff7401de52f14fc4dcef1914f5b4c48423580c1632a9a33d230cdb117f6cf44"
}
{
  "name": "meep-webhook",
  "version": "meep-docker-registry:30001/meep-webhook:latest",
  "id": "9b9c321751c640ba450bac3601530db330e3a50789df8e71e491fb643aeb8e41",
  "build": "d6af3ed55530d0d40b7f7e649db3ef87ffa2651dc5c1819a10cb5fe114394ceb"
}
```

**AdvantEDGE node:**
Information on the node where AdvantEDGE is running
Virtual Machine with the following characteristics
- OS: Ubuntu 20.04.2.0 Desktop x64
- CPUs: 22
- Memory: 32GB
- Storage: 64GB

**Additional context**
When using `kubectl describe` to look into the pods state, it seems to be stuck in `PodInitializing` all of the 15 minutes with `Restart Count:  0`.  Below, the events when looking into the sandbox control pod:
```
Events:
  Type    Reason     Age   From                                        Message
  ----    ------     ----  ----                                        -------
  Normal  Scheduled  16m   default-scheduler                           Successfully assigned sandbox-diag/meep-sandbox-ctrl-586cb9d6d4-n97j7 to juan-standard-pc-i440fx-piix-1996
  Normal  Pulled     16m   kubelet, juan-standard-pc-i440fx-piix-1996  Container image "busybox:1.28" already present on machine
  Normal  Created    16m   kubelet, juan-standard-pc-i440fx-piix-1996  Created container init-kube-dns
  Normal  Started    16m   kubelet, juan-standard-pc-i440fx-piix-1996  Started container init-kube-dns
  Normal  Pulling    97s   kubelet, juan-standard-pc-i440fx-piix-1996  Pulling image "meep-docker-registry:30001/meep-sandbox-ctrl:latest"
  Normal  Pulled     97s   kubelet, juan-standard-pc-i440fx-piix-1996  Successfully pulled image "meep-docker-registry:30001/meep-sandbox-ctrl:latest" in 28.280311ms
  Normal  Created    96s   kubelet, juan-standard-pc-i440fx-piix-1996  Created container meep-sandbox-ctrl
  Normal  Started    96s   kubelet, juan-standard-pc-i440fx-piix-1996  Started container meep-sandbox-ctrl
```

Below is the output of describe for the application pod (events) of the time it took the 15 minutes. This behavior is strange because deploying the same pod manually (With `kubectl`) is much faster.
 
```
Events:
  Type    Reason     Age   From                                        Message
  ----    ------     ----  ----                                        -------
  Normal  Scheduled  16m   default-scheduler                           Successfully assigned sandbox-diag/diagnostics-client-app-6c97686bbb-x7zhd to juan-standard-pc-i440fx-piix-1996
  Normal  Pulled     16m   kubelet, juan-standard-pc-i440fx-piix-1996  Container image "busybox:1.28" already present on machine
  Normal  Created    16m   kubelet, juan-standard-pc-i440fx-piix-1996  Created container init-kube-dns
  Normal  Started    16m   kubelet, juan-standard-pc-i440fx-piix-1996  Started container init-kube-dns
  Normal  Pulling    104s  kubelet, juan-standard-pc-i440fx-piix-1996  Pulling image "jpcr3108/diagnostics_client:v1.5"
  Normal  Pulled     103s  kubelet, juan-standard-pc-i440fx-piix-1996  Successfully pulled image "jpcr3108/diagnostics_client:v1.5" in 1.651923307s
  Normal  Created    102s  kubelet, juan-standard-pc-i440fx-piix-1996  Created container diagnostics-client-app
  Normal  Started    102s  kubelet, juan-standard-pc-i440fx-piix-1996  Started container diagnostics-client-app
  Normal  Pulling    102s  kubelet, juan-standard-pc-i440fx-piix-1996  Pulling image "meep-docker-registry:30001/meep-tc-sidecar:latest"
  Normal  Pulled     102s  kubelet, juan-standard-pc-i440fx-piix-1996  Successfully pulled image "meep-docker-registry:30001/meep-tc-sidecar:latest" in 16.461287ms
  Normal  Created    102s  kubelet, juan-standard-pc-i440fx-piix-1996  Created container meep-tc-sidecar
  Normal  Started    102s  kubelet, juan-standard-pc-i440fx-piix-1996  Started container meep-tc-sidecar
```

**Comment by dilallkx** [comment]
Hi @juan-castrillon,

Thank you for reporting this issue!
I have not yet observed this behavior with release v1.6.0 on my setups, however I have seen a similar issue while testing v1.7.0 on new deployments (although in my case it seemed to occur only when I created a large number of pods, e.g. ~90+). I am currently investigating the problem and I will let you know if I need additional information to help debug the issue.

One question for now, were you running any additional pods on your k8s cluster or did you only install the AdvantEDGE platform with a single sandbox?

Thanks!

**Comment by juan-castrillon** [comment]
Hello @dilallkx !

Thank you for your answer :)

In addition to the AE pods, these are the only ones running (all from kubesystem):
![image](https://user-images.githubusercontent.com/64461123/117798380-631ef380-b251-11eb-805f-2d25cd70b7b4.png)

Apart from that, I just use AE in this VM. So I had only the meep pods and the pods for one sandbox in the cluster.

If you need to know anything else just let me know.

**Comment by dilallkx** [comment]
Hi @juan-castrillon,

I have not identified the cause yet, however I no longer observe the issue when I downgrade to k8s version 1.18. Could you give this a try on your VM to see if it fixes the problem you are observing?

To downgrade k8s to v1.18, you can follow the steps from the wiki here:
https://github.com/InterDigitalInc/AdvantEDGE/wiki/env-runtime#step-3---install-kubeadm-kubelet--kubectl-details

The only difference in the procedure is to set the kubeadm version to 1.18 while installing, as follows:
```
# Install latest supported k8s version
sudo apt-get update
sudo apt-get install -y kubelet=1.18.1-00 kubeadm=1.18.1-00 kubectl=1.18.1-00 kubernetes-cni=0.8.7-00
```

Hopefully this workaround fixes your issue for now, at least temporarily while I work on addressing this on k8s v1.19+ setups.

Thanks!

**Comment by dilallkx** [comment]
Hi @juan-castrillon,

After some more investigation I have determined that the issue seems to occur only with the latest version of containerd (installed during Docker installation). Running `docker version` on my working setup returns the following:

```
Client: Docker Engine - Community
 Version:           19.03.15
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        99e3ed8919
 Built:             Sat Jan 30 03:16:51 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       99e3ed8919
  Built:            Sat Jan 30 03:15:20 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Kubernetes states that they support docker version 19.03; however, they do not specify a supported containerd version. The Docker installation procedure for Ubuntu is described here:
https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

This procedure installs the latest ubuntu package _containerd.io_ (currently version 1.4.4). This containerd version seems to cause problems when used with Kubernetes (tested with v1.19 & v1.20) & weave CNI plugin (tested with v2.6.2 & v2.8.1). I observe a maximum pod count of ~52 pods instead of the maximum allocatable value of 110. After 52 pods the pods remain stuck in PodInitializing or Creating state.

If you have a containerd version more recent than v1.3.7 this could also explain the behavior you are observing.

To fix this issue on my setup I reinstalled Kubernetes (Kubeadm) & Docker, bolting down the Docker & containerd versions. To do so, you must follow these steps:

1. Uninstall Kubeadm:
https://github.com/InterDigitalInc/AdvantEDGE/wiki/env-runtime#step-3---install-kubeadm-kubelet--kubectl-details
2. Uninstall docker:
https://docs.docker.com/engine/install/ubuntu/#uninstall-docker-engine
3. Reboot machine
4. Install docker
NOTE: Use the following command to set specific docker & containerd versions:
`sudo apt-get install docker-ce=5:19.03.15~3-0~ubuntu-bionic docker-ce-cli=5:19.03.15~3-0~ubuntu-bionic containerd.io=1.3.7-1`
https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
5. Make sure docker daemon is configured to use systemd cgoup driver:
https://github.com/InterDigitalInc/AdvantEDGE/wiki/env-runtime#step-2---setup-docker-daemon-details
6. Install Kubernetes
NOTE: You can use the latest stable 1.20 release by installing these package versions:
`sudo apt-get install -y kubelet=1.20.6-00 kubeadm=1.20.6-00 kubectl=1.20.6-00 kubernetes-cni=0.8.7-00`
https://github.com/InterDigitalInc/AdvantEDGE/wiki/env-runtime#step-3---install-kubeadm-kubelet--kubectl-details
7. Complete kubeadm installation steps (up to step 7)
https://github.com/InterDigitalInc/AdvantEDGE/wiki/env-runtime#step-4---initialize-master-details

Once installed you can deploy the AdvantEDGE platform dependencies (this may take some time to download the images you may have removed during docker uninstall) and the AdvantEDGE core microservices. At this point the platform should be up & running and in a good state.

Please give this a try and let me know if it fixes the issues you have observed.

Thanks!

**Comment by roymx** [comment]
Moved to [this discussion ](https://github.com/InterDigitalInc/AdvantEDGE/discussions/348)
