### ISSUE TITLE
[Location-Service] GET /etsi-013/location/v1/users response non-conformance

### ISSUE THREAD

**Issue by roymx** [InterDigitalInc/AdvantEDGE#27]
Originally reported by @YannGarcia

**Describe the bug**
The response to request **GET /etsi-013/location/v1/users** is missing the *userList* field
'{"user":[{"address...'

**To Reproduce**
GET /etsi-013/location/v1/users

**Expected behavior**
Response is compliant with [ETSI APIs](https://forge.etsi.org/swagger/ui/?url=https://forge.etsi.org/gitlab/mec/gs013-location-api/raw/master/LocationAPI.yaml#/operations/users/usersGet) and shows both *userList* and *user* levels

**AdvantEDGE versions**
1.2.0

**Comment by roymx** [comment]
Included in v1.3.0 release

**Comment by YannGarcia** [comment]
Hello Mike,

Thanks a lot for the information, I'll try it asap ;)

Best regards,

Yann Garcia
Senior Software Engineer
Microsoft MCAD.net Certified
**************************************
FSCOM SARL
Le Montespan B2
6,
<https://maps.google.com/?q=6,%C2%A0+Avenue+des+Alpes&entry=gmail&source=g>
  Avenue des Alpes
<https://maps.google.com/?q=6,%C2%A0+Avenue+des+Alpes&entry=gmail&source=g>
F-06600 Antibes, FRANCE
************************************************
Tel: +33 (0)4 92 94 49 08
Mobile: +33 (0)6 68 94 57 76
Email: *yann.garcia@fscom.fr <yann.garcia@fscom.fr>*
Skype: yann.garcia

**Comment by YannGarcia** [comment]
Hello Mike,

I update and rebuild AdvantEDGE, but I have an errors when I try to deploy
dep and core.
I addition, when I execute the command 'kubectl get pods --all-namespaces',
I got: Unable to connect to the server: dial tcp 10.0.2.15:6443: i/o timeout
Where can I find the logs please?

Thanks a lot,

Best regards,

Yann Garcia
Senior Software Engineer
Microsoft MCAD.net Certified
**************************************
FSCOM SARL
Le Montespan B2
6,
<https://maps.google.com/?q=6,%C2%A0+Avenue+des+Alpes&entry=gmail&source=g>
  Avenue des Alpes
<https://maps.google.com/?q=6,%C2%A0+Avenue+des+Alpes&entry=gmail&source=g>
F-06600 Antibes, FRANCE
************************************************
Tel: +33 (0)4 92 94 49 08
Mobile: +33 (0)6 68 94 57 76
Email: *yann.garcia@fscom.fr <yann.garcia@fscom.fr>*
Skype: yann.garcia
