### ISSUE TITLE
meep-frontend kept on crashing

### ISSUE THREAD

**Issue by theodorelu27** [InterDigitalInc/AdvantEDGE#291]
**Describe the bug**
After some time, when accessing the meep frontend in localhost, it returns 500: Internal Server Error
restarting core and dep (with delete and deploy) does not help
reinstalling meep (install, build, dockerize) does not help
reinstalling docker and kubernetes sometimes help (out of 2 iteration, it help on 1 iteration and does not help on the second iteration)

**To Reproduce**
1. Access the AdvantEDGE dashboard via browser / curl

**Expected behavior**
The AdvantEDGE dashboard is opened normally

**Screenshots**
![image](https://user-images.githubusercontent.com/12758306/129428868-44c00f2b-798d-4c05-9c85-60a2201f3fde.png)

![image](https://user-images.githubusercontent.com/12758306/129419578-c091f948-2a1a-465f-acc4-17ec50a0e4ea.png)

**AdvantEDGE versions**
{
  "name": "meepctl",
  "version": "1.7.1"
}
{
  "name": ".meepctl-repocfg.yaml",
  "version": "1.7.1"
}
{
  "name": "meep-cert-manager",
  "version": "NA"
}
{
  "name": "couchdb",
  "version": "couchdb:3.1.0",
  "id": "b604d056d8024f10346eab768de7aea06bc0a1b7c55d6087e1b1cd4328c8061c"
}
{
  "name": "docker-registry",
  "version": "registry:2.7.1",
  "id": "bac2d7050dc4826516650267fe7dc6627e9e11ad653daca0641437abdf18df27"
}
{
  "name": "grafana",
  "version": "grafana/grafana:7.3.5",
  "id": "511bc20bfcd1b79f3947bb1c33d152f7484e7a91418883fb4dddf71274227321"
}
{
  "name": "meep-influxdb",
  "version": "influxdb:1.8.0-alpine",
  "id": "5eca9dfe9930a3325323cef801827eb1b0940070465f8f215447b8e732c72b34"
}
{
  "name": "meep-ingress",
  "version": "NA"
}
{
  "name": "kube-state-metrics",
  "version": "quay.io/coreos/kube-state-metrics:v1.9.7",
  "id": "2f82f0da199c60a7699c43c63a295c44e673242de0b7ee1b17c2d5a23bec34cb"
}
{
  "name": "meep-open-map-tiles",
  "version": "NA"
}
{
  "name": "meep-postgis",
  "version": "postgis/postgis:12-3.0",
  "id": "71acda16357f2973034483a4a8363cc9499061120b592bcc3b7f2fbed82da621"
}
{
  "name": "meep-prometheus",
  "version": "NA"
}
{
  "name": "meep-redis",
  "version": "NA"
}
{
  "name": "helm",
  "version": "v3.3.4",
  "id": "a61ce5633af99708171414353ed49547cf05013d"
}
{
  "name": "docker client",
  "version": "20.10.6",
  "id": "370c289"
}
{
  "name": "docker server",
  "id": "go1.13.15"
}
{
  "name": "k8s client",
  "version": "v1.19.1",
  "id": "206bcadf021e76c27513500ca24182692aabd17e"
}
{
  "name": "k8s server",
  "version": "v1.19.11",
  "id": "c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33"
}
{
  "name": "weave",
  "version": "weaveworks/weave-kube:2.8.1",
  "id": "d797338e7beb17222e10757b71400d8471bdbd9be13b5da38ce2ebf597fb4e63"
}
{
  "name": "meep-auth-svc",
  "version": "NA"
}
{
  "name": "meep-ingress-certs",
  "version": "NA"
}
{
  "name": "meep-mon-engine",
  "version": "NA"
}
{
  "name": "meep-platform-ctrl",
  "version": "NA"
}
{
  "name": "meep-virt-engine",
  "version": "NA"
}
{
  "name": "meep-webhook",
  "version": "NA"
}

**Front-end node:**
Information on the node where AdvantEDGE is running
 - OS: Ubuntu 
 - Node IP address: 172.17.0.1
 - Version 20.04.2 LTS (focal)
If applicable, information on applications used to reproduce the issue
 - Application Mozilla Firefox
 - Version 91.0

**Comment by dilallkx** [comment]
Hi @theodorelu27,

Thank you for reaching out!

I have a few clarification questions to better understand the issue you are observing:
- You mention in the description that you observe the issue "after some time". Were you able to successfully load the platform frontend in your browser previously? Did it suddenly stop working?
- Do you observe the issue with another browser (e.g. chrome)?
- Did you observe any _build_ or _dockerize_ errors?

Could you also please provide the following information from your setup:
- Output of `kubectl describe nodes`
- Output of `kubectl get pods --all-namespaces` when the issue occurs

Thank you!

**Comment by theodorelu27** [comment]
Hi @dilallkx , at the moment thankfully it's working, but I'd look out if it ever happened again

_You mention in the description that you observe the issue "after some time". Were you able to successfully load the platform frontend in your browser previously? Did it suddenly stop working?_

Yes, when it happened the platform stopped working in the middle of deployments and redeployment didn't do anything
Now a restart after destroying both core and dep helps, but as I mentioned in my initial post, when it breaks it's pretty persistent and would come back pretty quickly

_Do you observe the issue with another browser (e.g. chrome)?_

I haven't as only Firefox is available in my VM

_Did you observe any build or dockerize errors?_

Yes, in my case even on a fresh install, I experience linting error during the build
Error on dockerize is usually preceded by an error in building

_Output of kubectl describe nodes_

Is there any specific part of it or would you need everything?

_Output of kubectl get pods --all-namespaces when the issue occurs_

I don't have them, I'm still pretty new to kube so I wasn't sure which information are important to keep, I'd keep a lookout if the issue arises again

**Comment by dilallkx** [comment]
Hi @theodorelu27,

Thank you for the response!
I am glad to see it is working at the moment.

To further debug the issue you observed:
- For the build/dockerize issues, this should not occur. Please provide output for the `meepctl build all -v` and `meepctl dockerize -v` when the error occurs to help identify the root cause.
- For the `kubectl describe nodes` command, please provide the complete output. I would like to see if you are having node/resource errors that could explain your observed behavior.

Thanks!

**Comment by theodorelu27** [comment]
Hi @dilallkx ,

Okay, when I'm done with my current work, I'd retry the build and dockerize to see if it's still there

Meanwhile, here's the output of my `kubectl describe nodes` 

`Name:               edp-standard-pc-i440fx-piix-1996
Roles:              control-plane,master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=edp-standard-pc-i440fx-piix-1996
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=
                    node-role.kubernetes.io/master=
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sat, 14 Aug 2021 00:55:57 +0200
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  edp-standard-pc-i440fx-piix-1996
  AcquireTime:     <unset>
  RenewTime:       Thu, 02 Sep 2021 14:04:29 +0200
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Mon, 30 Aug 2021 17:42:55 +0200   Mon, 30 Aug 2021 17:42:55 +0200   WeaveIsUp                    Weave pod has set this
  MemoryPressure       False   Thu, 02 Sep 2021 14:01:03 +0200   Sat, 14 Aug 2021 00:55:56 +0200   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Thu, 02 Sep 2021 14:01:03 +0200   Sat, 14 Aug 2021 00:55:56 +0200   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Thu, 02 Sep 2021 14:01:03 +0200   Sat, 14 Aug 2021 00:55:56 +0200   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Thu, 02 Sep 2021 14:01:03 +0200   Sat, 14 Aug 2021 00:56:07 +0200   KubeletReady                 kubelet is posting ready status. AppArmor enabled
Addresses:
  InternalIP:  192.168.122.108
  Hostname:    edp-standard-pc-i440fx-piix-1996
Capacity:
  cpu:                22
  ephemeral-storage:  65274444Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             32881908Ki
  pods:               110
Allocatable:
  cpu:                22
  ephemeral-storage:  60156927491
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             32779508Ki
  pods:               110
System Info:
  Machine ID:                 09e235f454ce46d8a964af4d0aec0628
  System UUID:                43b34904-3d14-41c3-a757-581669fd1284
  Boot ID:                    ae3fd254-17d8-4a81-a22e-8ae69eb0a90f
  Kernel Version:             5.11.0-27-generic
  OS Image:                   Ubuntu 20.04.2 LTS
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://19.3.15
  Kubelet Version:            v1.20.6
  Kube-Proxy Version:         v1.20.6
Non-terminated Pods:          (36 in total)
  Namespace                   Name                                                        CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----                                                        ------------  ----------  ---------------  -------------  ---
  default                     meep-auth-svc-68fb4dbffd-njmbs                              0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-couchdb-couchdb-0                                      0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-docker-registry-65b77797cb-lbsxc                       0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-grafana-fd84cc684-w2phh                                0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-influxdb-0                                             0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-ingress-controller-gg894                               100m (0%)     0 (0%)      90Mi (0%)        0 (0%)         2d20h
  default                     meep-ingress-defaultbackend-5c57d5cd58-l57lb                0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-kube-state-metrics-868576f6d4-hrkr4                    0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-mon-engine-6b75855c74-cnqvm                            0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-open-map-tiles-7d99b886f-74zbq                         0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-platform-ctrl-5994bb5868-2tjx6                         0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-postgis-0                                              250m (1%)     0 (0%)      256Mi (0%)       0 (0%)         2d20h
  default                     meep-prometheus-couchdb-exporter-795d6b6dc5-k4frk           0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-prometheus-node-exporter-xv2j9                         0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-prometheus-operator-c8b8896d7-pt4vc                    0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-redis-master-0                                         0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-redis-slave-0                                          0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-virt-engine-6c46768bb-22kfk                            0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     meep-webhook-6865678784-kz2kt                               0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d20h
  default                     prometheus-meep-prometheus-server-0                         100m (0%)     100m (0%)   50Mi (0%)        50Mi (0%)      2d20h
  kube-system                 coredns-74ff55c5b-cr4kv                                     100m (0%)     0 (0%)      70Mi (0%)        170Mi (0%)     19d
  kube-system                 coredns-74ff55c5b-rgbqz                                     100m (0%)     0 (0%)      70Mi (0%)        170Mi (0%)     19d
  kube-system                 etcd-edp-standard-pc-i440fx-piix-1996                       100m (0%)     0 (0%)      100Mi (0%)       0 (0%)         19d
  kube-system                 kube-apiserver-edp-standard-pc-i440fx-piix-1996             250m (1%)     0 (0%)      0 (0%)           0 (0%)         19d
  kube-system                 kube-controller-manager-edp-standard-pc-i440fx-piix-1996    200m (0%)     0 (0%)      0 (0%)           0 (0%)         19d
  kube-system                 kube-proxy-9hbsx                                            0 (0%)        0 (0%)      0 (0%)           0 (0%)         19d
  kube-system                 kube-scheduler-edp-standard-pc-i440fx-piix-1996             100m (0%)     0 (0%)      0 (0%)           0 (0%)         19d
  kube-system                 weave-net-q9nns                                             100m (0%)     0 (0%)      200Mi (0%)       0 (0%)         19d
  man-check                   meep-gis-engine-5cccc4f96b-lnckl                            0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d19h
  man-check                   meep-loc-serv-59fc649fbd-lzsk5                              0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d19h
  man-check                   meep-metrics-engine-86bcbf768-47dbr                         0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d19h
  man-check                   meep-mg-manager-67d5859cf8-4qhj9                            0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d19h
  man-check                   meep-rnis-5665747bcf-mvs4q                                  0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d19h
  man-check                   meep-sandbox-ctrl-557875875c-7zchp                          0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d19h
  man-check                   meep-tc-engine-b7c6c6b94-hdptl                              0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d19h
  man-check                   meep-wais-56d74f66bd-587h9                                  0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d19h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                1400m (6%)  100m (0%)
  memory             836Mi (2%)  390Mi (1%)
  ephemeral-storage  100Mi (0%)  0 (0%)
  hugepages-1Gi      0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
Events:              <none>
`

Hope it helps!

**Comment by roymx** [comment]
closed - no more activity
