### ISSUE TITLE
Weave Installation Failing

### ISSUE THREAD

**Issue by jblakley** [InterDigitalInc/AdvantEDGE#405]
Release 1.8.0 and 1.8.1
With the shut down of weave, the old instructions for installing weave during k8s bring-up no longer work.

OLD:
`kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&env.WEAVE_MTU=1500"`

NEW:
`kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s-1.11.yaml`

**Comment by dilallkx** [comment]
Hi @jblakley,
Thank you for pointing this out. I have updated the documentation accordingly.
Note that we are working on updates to support the latest k8s release version and will be validating the full installation procedure shortly. We will include any additional installation fixes.
Thanks & regards!

**Comment by jblakley** [comment]
@dilallkx Thanks for the quick fix! Hope you all are well!

**Comment by dilallkx** [comment]
@jblakley Keeping busy :) Thanks again for reporting the issue!
