### ISSUE TITLE
Mobility event of Edge node not working

### ISSUE THREAD

**Issue by roymx** [InterDigitalInc/AdvantEDGE#93]
**Describe the bug**
Generating a mobility event towards an edge node does not always work.
Sometimes node moves, sometimes not
Sometimes breaks the Network Topology 

**To Reproduce**
1. Deploy demo 1
2. Generate a mobility event for Zone1-Edge1 to Zone2

**Expected behavior**
Zone1-Edge1 moves to Zone2

**Scenario**
Demo1

**AdvantEDGE versions**
meepctl version all
Using repo config file: /home/englab/AdvantEDGE/.meepctl-repocfg.yaml
Using meepctl config file: /home/englab/.meepctl.yaml
{
  "name": "meepctl",
  "version": "1.4.4"
}
{
  "name": ".meepctl-repocfg.yaml",
  "version": "1.4.4"
}
{
  "name": "couchdb",
  "version": "couchdb:2.1.1",
  "id": "c467d1c2a172bf0c8172b2e1c760686d0c7656d786e6874a9de12f2d0a3a38e7"
}
{
  "name": "docker-registry",
  "version": "registry:2.7.1",
  "id": "7d081088e4bfd632a88e3f3bcd9e007ef44a796fddfe3261407a3f9f04abe1e7"
}
{
  "name": "grafana",
  "version": "grafana/grafana:6.5.2",
  "id": "33d78da1e5f3f74833de2ba9303ddcf995da551850cf431696efd271e7928f9e"
}
{
  "name": "meep-influxdb",
  "version": "influxdb:1.7.6-alpine",
  "id": "4ba363315807fc6e35e98bc9d4760f417a681e4d3a547a0b24b135c56af96376"
}
{
  "name": "nginx-ingress-controller",
  "version": "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.30.0",
  "id": "b312c91d0de688a21075078982b5e3a48b13b46eda4df743317d3059fc3ca0d9"
}
{
  "name": "kube-state-metrics",
  "version": "quay.io/coreos/kube-state-metrics:v1.4.0",
  "id": "6685342bbd645754b1aabdd9b663691109ec680645af261288289e62571ac201"
}
{
  "name": "meep-open-map-tiles",
  "version": "NA"
}
{
  "name": "meep-postgis",
  "version": "postgis/postgis:12-3.0",
  "id": "7393c15282699140b6be300629bf92d414ff108573a503e97055bb1f36a2892b"
}
{
  "name": "meep-redis",
  "version": "redislabs/rejson:1.0.4",
  "id": "08f1d67dacae984c17aa9869b05415abd453cdd642623718301267455d3e2696"
}
{
  "name": "helm client",
  "version": "v2.16.7",
  "id": "5f2584fd3d35552c4af26036f0c464191287986b"
}
{
  "name": "helm server",
  "version": "v2.16.3",
  "id": "1ee0254c86d4ed6887327dabed7aa7da29d7eb0d"
}
{
  "name": "docker client",
  "version": "19.03.8",
  "id": "afacb8b7f0"
}
{
  "name": "docker server",
  "version": "19.03.8",
  "id": "afacb8b7f0"
}
{
  "name": "k8s client",
  "version": "v1.15.4",
  "id": "67d2fcf276fcd9cf743ad4be9a9ef5828adc082f"
}
{
  "name": "k8s server",
  "version": "v1.15.11",
  "id": "d94a81c724ea8e1ccc9002d89b7fe81d58f89ede"
}
{
  "name": "weave",
  "version": "weaveworks/weave-kube:2.6.1",
  "id": "cb97f901917623ed95cd07c63a79c09dd3ad9b7172fca055817bf749fe4e41fd"
}
{
  "name": "meep-mon-engine",
  "version": "meep-docker-registry:30001/meep-mon-engine:latest",
  "id": "88cca0fa377fa0dc0f86aed08cd515f52c8f124cfc332204cd70cd753521fbcd",
  "build": "d716c59b531ee794d9b4e97fc4dc3520d2d04e1cb776643c3bb92be2073ce869"
}
{
  "name": "meep-platform-ctrl",
  "version": "meep-docker-registry:30001/meep-platform-ctrl:latest",
  "id": "0fc215eed696e3a6b2d4e3819d30d792c6bf3d9f0128085031b96a90344e5403",
  "build": "7a0f4da596664c8c9653e77353aaa3574870e3f999dffde19eee36468968c3a3"
}
{
  "name": "meep-virt-engine",
  "version": "meep-docker-registry:30001/meep-virt-engine:latest",
  "id": "33f8442cb36dace92af9f673890869b76f713cc04b50a9df85b6ec06c1ae63bc",
  "build": "f8d8325b51f7d6fe62a61605178a980b030204e37fa202e7e7bc4e4df8735be4"
}
{
  "name": "meep-webhook",
  "version": "meep-docker-registry:30001/meep-webhook:latest",
  "id": "cf5665cd080113d7557e7bcb1c48e97d0a8e7dbe767092b2211292f98e49981f",
  "build": "35573e225232b9dce9f6038955e3b188aacd3a3f193853cf258fdb1b56a3e7f5"
}

**AdvantEDGE node:**
 - OS: Ubuntu 18.04 LTS

**Comment by dilallkx** [comment]
Issue resolved in PR #161.
Fix included in AdvantEDGE release v1.6.0.
